language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true

branches:
  only:
    - master

before_install:
 - if [[ $TRAVIS_TAG && "${TRAVIS_PHP_VERSION:0:3}" == "7.1" ]]; then wget -O sami.phar http://get.sensiolabs.org/sami.phar; fi

install:
  - composer self-update
  - composer install

script:
 - vendor/bin/parallel-lint src/
 - vendor/bin/parallel-lint tests/
 - vendor/bin/phpunit -v
 - if [[ $TRAVIS_TAG && "${TRAVIS_PHP_VERSION:0:3}" == "7.1" ]]; then ./scripts/prepare-docs.sh; fi

after_success:
 - travis_retry bash <(curl -s https://codecov.io/bash) -f build/logs/clover.xml

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: full/build/gh-pages
  on:
    php: 7.1
    tags: true
