language: php

git:
  depth: 1

env:
  global:
    - GH_REPO="github.com/${TRAVIS_REPO_SLUG}.git"
    - BUILD_LEAD=0
    - SYNTAX_TEST=0

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYNTAX_TEST=1
    - php: 7.0
    - php: 7.1
      env: BUILD_LEAD=1
    - php: 7.2

branches:
  only:
    - master

before_install:
  - |
    # Disable XDebug
    #
    # XDebug makes PHPUnit and PHP-CS-Fixer slow.
    # We need it only for generating the code coverage report,
    # so we disable it everywhere but for the build lead.
    if [ $BUILD_LEAD == 0 ]
    then
      phpenv config-rm xdebug.ini
    fi

install:
  - |
    # Install dependencies
    # We don't need to install dependencies when doing the syntax check.
    if [ $SYNTAX_TEST == 0 ]
    then
      composer install
    fi

script:
  - |
    # PHPUnit tests
    if [ $SYNTAX_TEST == 0 ]
    then
      php vendor/bin/phpunit --stop-on-error --stop-on-failure -v
    fi

  - |
    # Syntax tests
    #
    # We use PHP-CS-Fixer to check for syntax and style errors,
    # but we run a separate build for that to take advantage of build parallelism.
    if [ $SYNTAX_TEST == 1 ]
    then
      wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -q -O php-cs-fixer.phar
      php php-cs-fixer.phar fix --dry-run --stop-on-violation -v
    fi

after_success:
  - |
    # Upload code coverage
    #
    # The code coverage report is only generated when BUILD_LEAD is 1.
    if [ $BUILD_LEAD == 1 ]
    then
      travis_retry bash <(curl -s https://codecov.io/bash) -f build/logs/clover.xml
    fi

  - |
    # Generate API docs
    #
    # We generate API docs only for the build lead (to avoid wasting time on all builds),
    # and when on merges to master, which is the result of this condition and the setting
    # branches: only: master above.
    if [[ ($TRAVIS_PULL_REQUEST == false || $TRAVIS_TAG != false) && $BUILD_LEAD == 1 ]]
    then
      sh ./scripts/prepare-docs.sh
    fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/docs
  on:
    condition: ($TRAVIS_PULL_REQUEST == false || $TRAVIS_TAG != false) && $BUILD_LEAD == 1

notifications:
  slack:
    secure: VwV9TggMVDEuGcvklEhdlOHWG4uUSaw6tkPrOyaA2AJl8G+CYJ1/RwNXli8GGObWSdLi30uNUx1X1PXpW5dL2sN3+zMd4r2opbaWNQg8oQ1mB8U+z0wzVa3LVNufBNCJYeIvDsMrJG3S51ndzIk7NNKHcXB/bnLE0St3w8L18P7l3FknrQQUY4gIdTstscmLjQzxw1U7mAwELhigcUXJp9Ujm5MnnBqD3YDDojWt0M2n8FQVY/Ia9Ubk40kg+AGOAtBNbRteiaIGyxrvNjtTg33t4OcobjzgYEBIXFC796foNNp/AiH8cTeSB2UHMgUiLZbq7R2nuz1t2E6fOCrOD7Bg66okhz2hYV/sx8grlxinjwF5tjZS0ykC4RaIwVBkXlwgjH6J9zd5vS8dmQ1vP75RSER9kdksbvmhXAS7kAAKJ0dwRMFjKH/gMkx5vkz8FKlsuWs0n3x3IeWI0a2cGIJrRHvEJVhmWNJuHYliGHKH1Jw6DsjtqS3q5Xxv3zPJzHgjb0+NujRToGAgDj7jHy4diGbQKxVoydrJY1y2eLDQ2hF2uHA5LIIMI6Lb7Y/My/Op9p5RyH0HJ5uKdvT3Dc447n5q5LQXHxBh5otEM3t81NpPos62QmIq38JkYVx9A1YoogRz7J3GuChhOD5Ha/4I26cxjinmmJdbsm5akJg=
